#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Comparison_shopping_engine_frontend_android.Resource", IsApplication=true)]

namespace Comparison_shopping_engine_frontend_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::Comparison_shopping_engine_frontend_android.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::Comparison_shopping_engine_frontend_android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int Themes = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int configLinearLayout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int configSpinner = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int configTextView = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int fragmentLinearLayout = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int homeCameraButton = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int homeConfigButton = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int homeGalleryButton = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int homeImageView = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int homeLinearLayout = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int homeResultScreenButton = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int homeTextView = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int homeVLinearLayout = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int itemsLinearLayout = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int resultsButtonsLinearLayout = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int resultsLinearLayout = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int resultsNewItemButton = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int resultsScroll = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int resultsSubmitButton = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int resultsTextView = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Config = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Home = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PictureFragment = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Results = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int configSpinner = 2130903043;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
