//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comparison_shopping_engine_frontend_android {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comparison_shopping_engine_frontend_android.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string AddNewItemButton {
            get {
                return ResourceManager.GetString("AddNewItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraButton {
            get {
                return ResourceManager.GetString("CameraButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing.
        /// </summary>
        public static string ComparingSpinner {
            get {
                return ResourceManager.GetString("ComparingSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string ConfigButton {
            get {
                return ResourceManager.GetString("ConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme:.
        /// </summary>
        public static string ConfigRequest {
            get {
                return ResourceManager.GetString("ConfigRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting image....
        /// </summary>
        public static string ConvertProgress {
            get {
                return ResourceManager.GetString("ConvertProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo from Gallery.
        /// </summary>
        public static string FromGalleryButton {
            get {
                return ResourceManager.GetString("FromGalleryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Screen.
        /// </summary>
        public static string HomeScreenText {
            get {
                return ResourceManager.GetString("HomeScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ItemDateHint {
            get {
                return ResourceManager.GetString("ItemDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        public static string ItemNameHint {
            get {
                return ResourceManager.GetString("ItemNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string ItemPriceHint {
            get {
                return ResourceManager.GetString("ItemPriceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string ItemStoreHint {
            get {
                return ResourceManager.GetString("ItemStoreHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string ParsingSpinner {
            get {
                return ResourceManager.GetString("ParsingSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any cheaper!.
        /// </summary>
        public static string PriceEqual {
            get {
                return ResourceManager.GetString("PriceEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could&apos;ve saved {0} in {1}!.
        /// </summary>
        public static string PriceLarger {
            get {
                return ResourceManager.GetString("PriceLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the first to get it!.
        /// </summary>
        public static string PriceSmaller {
            get {
                return ResourceManager.GetString("PriceSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Screen.
        /// </summary>
        public static string ResultScreenButton {
            get {
                return ResourceManager.GetString("ResultScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string SubmitErrorButton {
            get {
                return ResourceManager.GetString("SubmitErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields colored red have some issues in them.
        /// </summary>
        public static string SubmitErrorMessage {
            get {
                return ResourceManager.GetString("SubmitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few typos?.
        /// </summary>
        public static string SubmitErrorTitle {
            get {
                return ResourceManager.GetString("SubmitErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did we get it right?.
        /// </summary>
        public static string SubmitLabel {
            get {
                return ResourceManager.GetString("SubmitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops.
        /// </summary>
        public static string SubmitNoItemsButton {
            get {
                return ResourceManager.GetString("SubmitNoItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thought you could outplay me?.
        /// </summary>
        public static string SubmitNoItemsMessage {
            get {
                return ResourceManager.GetString("SubmitNoItemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are the items?.
        /// </summary>
        public static string SubmitNoItemsTitle {
            get {
                return ResourceManager.GetString("SubmitNoItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Photo.
        /// </summary>
        public static string SubmitPhotoButton {
            get {
                return ResourceManager.GetString("SubmitPhotoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Looks OK!.
        /// </summary>
        public static string SubmitReceiptButton {
            get {
                return ResourceManager.GetString("SubmitReceiptButton", resourceCulture);
            }
        }
    }
}
