language: csharp
solution: Comparison-shopping-engine.sln

env:
  global:
    - GH_REPO_NAME: Comparison-shopping-engine
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x build-doc.sh
  - ./build-doc.sh
