language: csharp
solution: Comparison-shopping-engine.sln

env:
  global:
    - GH_REPO_NAME: Comparison-shopping-engine
    - DOXYFILE: $TRAVIS_BUILD_DIR/Comparison-shopping-engine-documentation/Doxyfile
    - GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - nuget restore Comparison-shopping-engine.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - xbuild /p:Configuration=CI Comparison-shopping-engine.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Comparison-shopping-engine-backend.Tests/bin/CI/Comparison-shopping-engine-backend.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Comparison-shopping-engine-core-entities.Tests/bin/CI/Comparison-shopping-engine-core-entities.Tests.dll
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./Comparison-shopping-engine-web-protocol.Tests/bin/CI/Comparison-shopping-engine-web-protocol.Tests.dll


after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x Comparison-shopping-engine-documentation/build-doc.sh
  - Comparison-shopping-engine-documentation/build-doc.sh
