language: csharp
solution: Comparison-shopping-engine.sln

env:
  global:
    - GH_REPO_NAME: Comparison-shopping-engine
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=CI solution-name.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyProject.Tests/bin/CI/MyProject.Tests.dll

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x build-doc.sh
  - ./build-doc.sh
