# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: Comparison-shopping-engine
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x build-doc.sh
  - ./build-doc.sh
