version: 1.0.{build}-{APPVEYOR_REPO_COMMIT}

branches:
  except:
    - gh-pages

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\myproject

environment:
  GH_REPO_NAME: Comparison-shopping-engine
  GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

install:
  - nuget restore
  - choco install doxygen.portable
  - choco install graphviz

platform: Any CPU

configuration: CI

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Comparison-shopping-engine.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  verbosity: normal

after_test:
  - ps: doxygen.exe "C:\projects\myproject\Comparison-shopping-engine-documentation\Doxyfile"
  - git checkout gh-pages
  - ls .
  - rm -rf !(html)
  - ls .
  - echo "" > .nojekyll
  - echo build > .version
  - git add --all
  - git commit -m "Deploy code docs to GitHub Pages Appveyor build: ${APPVEYOR_BUILD_NUMBER}"
  - git push