version: 1.0.{build}

branches:
  except:
    - gh-pages

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\myproject

environment:
  GH_REPO_NAME: Comparison-shopping-engine
  GH_REPO_REF: github.com/gedgaudasnikita/Comparison-shopping-engine.git

install:
  - nuget restore
  - choco install doxygen.portable
  - choco install graphviz

platform: Any CPU

configuration: CI

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Comparison-shopping-engine.sln      # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  verbosity: normal

after_test:
  - git config --global credential.helper store
  - git config --global user.email "team@appveyor.com"
  - git config --global user.name "AppVeyor CI"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_REPO_TOKEN):x-oauth-basic@github.com`n"
  - git clone -b gh-pages https://git@github.com/gedgaudasnikita/Comparison-shopping-engine.git
  - cd Comparison-shopping-engine
  - rm -rf *  
  - echo "" > .nojekyll
  - echo build > .version
  - ps: doxygen.exe "C:\projects\myproject\Comparison-shopping-engine-documentation\Doxyfile"
  - cp -r html/* .
  - rm -rf html
  - git add --all
  - git commit -m "Deploy code docs to GitHub Pages Appveyor build:{build}"
  - echo %GH_REPO_TOKEN%
  - echo %GH_REPO_REF%
  - git push --force "https://%GH_REPO_TOKEN%@%GH_REPO_REF%"