var searchData=
[
  ['parse',['Parse',['../classComparison__shopping__engine__backend_1_1ParseableReceipt.html#a5e155ef9464b33bdea709da895cbfc0c',1,'Comparison_shopping_engine_backend.ParseableReceipt.Parse()'],['../interfaceComparison__shopping__engine__backend_1_1IParser_3_01T_01_4.html#a52b29366b8639fa7af32dd6021728cd0',1,'Comparison_shopping_engine_backend.IParser&lt; T &gt;.Parse()'],['../classComparison__shopping__engine__backend_1_1DateParser.html#a456bd6aba4faa2f13b915555c3a8c316',1,'Comparison_shopping_engine_backend.DateParser.Parse()'],['../classComparison__shopping__engine__backend_1_1ItemListParser.html#aa2a981611e07413dbabe8256fa8ec090',1,'Comparison_shopping_engine_backend.ItemListParser.Parse()'],['../classComparison__shopping__engine__backend_1_1StoreParser.html#a7c2a47ab0a30632f98d326c413a1f6e6',1,'Comparison_shopping_engine_backend.StoreParser.Parse()']]],
  ['parseablereceipt',['ParseableReceipt',['../classComparison__shopping__engine__backend_1_1ParseableReceipt.html',1,'Comparison_shopping_engine_backend']]],
  ['parseablereceipt_2ecs',['ParseableReceipt.cs',['../ParseableReceipt_8cs.html',1,'']]],
  ['parsingspinner',['ParsingSpinner',['../classComparison__shopping__engine__frontend__android_1_1AppResources.html#a10f025d7becd9d2480716c12460cc439',1,'Comparison_shopping_engine_frontend_android::AppResources']]],
  ['persist',['Persist',['../classComparison__shopping__engine__backend_1_1ItemManager.html#a3e0b98d96ba27ca8185b8c7da2b14c34',1,'Comparison_shopping_engine_backend.ItemManager.Persist()'],['../classComparison__shopping__engine__backend_1_1NormalizationEngine.html#aefa494c85f7e7fd3bbabd05e8adac3bc',1,'Comparison_shopping_engine_backend.NormalizationEngine.Persist()']]],
  ['price',['Price',['../classComparison__shopping__engine__core__entities_1_1Item.html#a459f76b9a4ceb612e457f8cf1d5ca764',1,'Comparison_shopping_engine_core_entities.Item.Price()'],['../classComparison__shopping__engine__frontend__android_1_1ItemLine.html#aacaee5e8ee8da18ec135e6be576f4a13',1,'Comparison_shopping_engine_frontend_android.ItemLine.Price()']]],
  ['priceequal',['PriceEqual',['../classComparison__shopping__engine__frontend__android_1_1AppResources.html#ad55417a0b2abeb7527ab747a0708d02f',1,'Comparison_shopping_engine_frontend_android::AppResources']]],
  ['pricelarger',['PriceLarger',['../classComparison__shopping__engine__frontend__android_1_1AppResources.html#a7de94294c6897257221b29d5d7042e15',1,'Comparison_shopping_engine_frontend_android::AppResources']]],
  ['pricesmaller',['PriceSmaller',['../classComparison__shopping__engine__frontend__android_1_1AppResources.html#af88764ad7f2626c7ff58ab80bca053a6',1,'Comparison_shopping_engine_frontend_android::AppResources']]],
  ['processimage',['ProcessImage',['../classComparison__shopping__engine__backend_1_1Controller.html#a793fd0831f5e664d95e78b60c7cc99d1',1,'Comparison_shopping_engine_backend.Controller.ProcessImage()'],['../classComparison__shopping__engine__frontend__android_1_1BackendInterface.html#a2742ed8332d4b4a249d4b5c8e908a409',1,'Comparison_shopping_engine_frontend_android.BackendInterface.ProcessImage()']]],
  ['processimagebackendendpoint',['ProcessImageBackendEndpoint',['../classComparison__shopping__engine__backend_1_1ProcessImageBackendEndpoint.html',1,'Comparison_shopping_engine_backend']]],
  ['processimagebackendendpoint_2ecs',['ProcessImageBackendEndpoint.cs',['../ProcessImageBackendEndpoint_8cs.html',1,'']]],
  ['processimageendpoint',['ProcessImageEndpoint',['../classComparison__shopping__engine__web__protocol_1_1ProcessImageEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['processimageendpoint_2ecs',['ProcessImageEndpoint.cs',['../ProcessImageEndpoint_8cs.html',1,'']]],
  ['processreceipt',['ProcessReceipt',['../classComparison__shopping__engine__backend_1_1Controller.html#a5fc39b82b02ecf4118f473f231cc7416',1,'Comparison_shopping_engine_backend.Controller.ProcessReceipt()'],['../classComparison__shopping__engine__frontend__android_1_1BackendInterface.html#a74ac3b895db75f2342d5fd3f839e79ec',1,'Comparison_shopping_engine_frontend_android.BackendInterface.ProcessReceipt()']]],
  ['processreceiptbackendendpoint',['ProcessReceiptBackendEndpoint',['../classComparison__shopping__engine__backend_1_1ProcessReceiptBackendEndpoint.html',1,'Comparison_shopping_engine_backend']]],
  ['processreceiptbackendendpoint_2ecs',['ProcessReceiptBackendEndpoint.cs',['../ProcessReceiptBackendEndpoint_8cs.html',1,'']]],
  ['processreceiptendpoint',['ProcessReceiptEndpoint',['../classComparison__shopping__engine__web__protocol_1_1ProcessReceiptEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['processreceiptendpoint_2ecs',['ProcessReceiptEndpoint.cs',['../ProcessReceiptEndpoint_8cs.html',1,'']]],
  ['program',['Program',['../classComparison__shopping__engine__backend_1_1Program.html',1,'Comparison_shopping_engine_backend']]],
  ['program_2ecs',['Program.cs',['../Program_8cs.html',1,'']]]
];
