var searchData=
[
  ['ibackendendpoint',['IBackendEndpoint',['../dd/d67/interfaceComparison__shopping__engine__backend_1_1IBackendEndpoint.html',1,'Comparison_shopping_engine_backend']]],
  ['icomparer',['IComparer',['../d7/de5/classIComparer.html',1,'']]],
  ['idisposable',['IDisposable',['../d0/d07/classIDisposable.html',1,'']]],
  ['iendpoint',['IEndpoint',['../d6/ddd/interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20object_2c_20getsuggestionsparameters_2c_20list_3c_20string_20_3e_20_3e',['IEndpoint&lt; object, GetSuggestionsParameters, List&lt; string &gt; &gt;',['../d6/ddd/interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20receipt_2c_20object_2c_20list_3c_20item_20_3e_20_3e',['IEndpoint&lt; Receipt, Object, List&lt; Item &gt; &gt;',['../d6/ddd/interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20receipt_2c_20object_2c_20object_20_3e',['IEndpoint&lt; Receipt, object, object &gt;',['../d6/ddd/interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20string_2c_20object_2c_20receipt_20_3e',['IEndpoint&lt; string, object, Receipt &gt;',['../d6/ddd/interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpointmeta',['IEndpointMeta',['../d4/d3b/interfaceComparison__shopping__engine__web__protocol_1_1IEndpointMeta.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iequatable',['IEquatable',['../d9/d1c/classIEquatable.html',1,'']]],
  ['iparser',['IParser',['../d1/d7a/interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['iparser_3c_20datetime_20_3e',['IParser&lt; DateTime &gt;',['../d1/d7a/interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['iparser_3c_20list_3c_20item_20_3e_3e',['IParser&lt; List&lt; Item &gt;&gt;',['../df/d0e/classIParser_3_01List_3_01Item_01_4_4.html',1,'']]],
  ['iparser_3c_20string_20_3e',['IParser&lt; string &gt;',['../d1/d7a/interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['irouter',['IRouter',['../d7/dbc/interfaceComparison__shopping__engine__backend_1_1IRouter.html',1,'Comparison_shopping_engine_backend']]],
  ['iserver',['IServer',['../dd/d96/interfaceComparison__shopping__engine__backend_1_1IServer.html',1,'Comparison_shopping_engine_backend']]],
  ['item',['Item',['../d1/d5d/classComparison__shopping__engine__core__entities_1_1Item.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemcorrectform',['ItemCorrectForm',['../d5/d83/classComparison__shopping__engine__admin_1_1ItemCorrectForm.html',1,'Comparison_shopping_engine_admin']]],
  ['itemdatecomparer',['ItemDateComparer',['../df/dc1/classComparison__shopping__engine__core__entities_1_1ItemDateComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemdateview',['ItemDateView',['../df/db5/classComparison__shopping__engine__frontend__android_1_1ItemDateView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemdeleteform',['ItemDeleteForm',['../d5/d85/classComparison__shopping__engine__admin_1_1ItemDeleteForm.html',1,'Comparison_shopping_engine_admin']]],
  ['itemdeleteview',['ItemDeleteView',['../d6/df2/classComparison__shopping__engine__frontend__android_1_1ItemDeleteView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemline',['ItemLine',['../d8/def/classComparison__shopping__engine__frontend__android_1_1ItemLine.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemlistparser',['ItemListParser',['../d5/d89/classComparison__shopping__engine__backend_1_1ItemListParser.html',1,'Comparison_shopping_engine_backend']]],
  ['itemmanager',['ItemManager',['../d3/ded/classComparison__shopping__engine__backend_1_1ItemManager.html',1,'Comparison_shopping_engine_backend']]],
  ['itemnamecomparer',['ItemNameComparer',['../d5/dae/classComparison__shopping__engine__core__entities_1_1ItemNameComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemnameview',['ItemNameView',['../da/d71/classComparison__shopping__engine__frontend__android_1_1ItemNameView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itempricecomparer',['ItemPriceComparer',['../da/df6/classComparison__shopping__engine__core__entities_1_1ItemPriceComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itempriceview',['ItemPriceView',['../d5/d16/classComparison__shopping__engine__frontend__android_1_1ItemPriceView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemstorecomparer',['ItemStoreComparer',['../dd/d6b/classComparison__shopping__engine__core__entities_1_1ItemStoreComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemstoreview',['ItemStoreView',['../d3/d0f/classComparison__shopping__engine__frontend__android_1_1ItemStoreView.html',1,'Comparison_shopping_engine_frontend_android']]]
];
