var searchData=
[
  ['ibackendendpoint',['IBackendEndpoint',['../interfaceComparison__shopping__engine__backend_1_1IBackendEndpoint.html',1,'Comparison_shopping_engine_backend']]],
  ['icomparer',['IComparer',['../classIComparer.html',1,'']]],
  ['id',['Id',['../classComparison__shopping__engine__frontend__android_1_1Resource_1_1Id.html',1,'Comparison_shopping_engine_frontend_android::Resource']]],
  ['idisposable',['IDisposable',['../classIDisposable.html',1,'']]],
  ['iendpoint',['IEndpoint',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20object_2c_20getsuggestionsparameters_2c_20list_3c_20string_20_3e_20_3e',['IEndpoint&lt; object, GetSuggestionsParameters, List&lt; string &gt; &gt;',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20receipt_2c_20object_2c_20list_3c_20item_20_3e_20_3e',['IEndpoint&lt; Receipt, Object, List&lt; Item &gt; &gt;',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20receipt_2c_20object_2c_20object_20_3e',['IEndpoint&lt; Receipt, object, object &gt;',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpoint_3c_20string_2c_20object_2c_20receipt_20_3e',['IEndpoint&lt; string, object, Receipt &gt;',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpoint.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iendpointmeta',['IEndpointMeta',['../interfaceComparison__shopping__engine__web__protocol_1_1IEndpointMeta.html',1,'Comparison_shopping_engine_web_protocol']]],
  ['iequatable',['IEquatable',['../classIEquatable.html',1,'']]],
  ['iparser',['IParser',['../interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['iparser_3c_20datetime_20_3e',['IParser&lt; DateTime &gt;',['../interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['iparser_3c_20list_3c_20item_20_3e_3e',['IParser&lt; List&lt; Item &gt;&gt;',['../classIParser_3_01List_3_01Item_01_4_4.html',1,'']]],
  ['iparser_3c_20string_20_3e',['IParser&lt; string &gt;',['../interfaceComparison__shopping__engine__backend_1_1IParser.html',1,'Comparison_shopping_engine_backend']]],
  ['irouter',['IRouter',['../interfaceComparison__shopping__engine__backend_1_1IRouter.html',1,'Comparison_shopping_engine_backend']]],
  ['iserver',['IServer',['../interfaceComparison__shopping__engine__backend_1_1IServer.html',1,'Comparison_shopping_engine_backend']]],
  ['item',['Item',['../classComparison__shopping__engine__core__entities_1_1Item.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemcorrectform',['ItemCorrectForm',['../classComparison__shopping__engine__admin_1_1ItemCorrectForm.html',1,'Comparison_shopping_engine_admin']]],
  ['itemdatecomparer',['ItemDateComparer',['../classComparison__shopping__engine__core__entities_1_1ItemDateComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemdateview',['ItemDateView',['../classComparison__shopping__engine__frontend__android_1_1ItemDateView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemdeleteform',['ItemDeleteForm',['../classComparison__shopping__engine__admin_1_1ItemDeleteForm.html',1,'Comparison_shopping_engine_admin']]],
  ['itemdeleteview',['ItemDeleteView',['../classComparison__shopping__engine__frontend__android_1_1ItemDeleteView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemline',['ItemLine',['../classComparison__shopping__engine__frontend__android_1_1ItemLine.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemlistparser',['ItemListParser',['../classComparison__shopping__engine__backend_1_1ItemListParser.html',1,'Comparison_shopping_engine_backend']]],
  ['itemmanager',['ItemManager',['../classComparison__shopping__engine__backend_1_1ItemManager.html',1,'Comparison_shopping_engine_backend']]],
  ['itemnamecomparer',['ItemNameComparer',['../classComparison__shopping__engine__core__entities_1_1ItemNameComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemnameview',['ItemNameView',['../classComparison__shopping__engine__frontend__android_1_1ItemNameView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itempricecomparer',['ItemPriceComparer',['../classComparison__shopping__engine__core__entities_1_1ItemPriceComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itempriceview',['ItemPriceView',['../classComparison__shopping__engine__frontend__android_1_1ItemPriceView.html',1,'Comparison_shopping_engine_frontend_android']]],
  ['itemstorecomparer',['ItemStoreComparer',['../classComparison__shopping__engine__core__entities_1_1ItemStoreComparer.html',1,'Comparison_shopping_engine_core_entities']]],
  ['itemstoreview',['ItemStoreView',['../classComparison__shopping__engine__frontend__android_1_1ItemStoreView.html',1,'Comparison_shopping_engine_frontend_android']]]
];
