#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Comparison_shopping_engine_frontend_android.Resource", IsApplication=true)]

namespace Comparison_shopping_engine_frontend_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Tesseract.Droid.Resource.String.ApplicationName = global::Comparison_shopping_engine_frontend_android.Resource.String.ApplicationName;
			global::Tesseract.Droid.Resource.String.Hello = global::Comparison_shopping_engine_frontend_android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public const int homeCameraButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int homeGalleryButton = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int homeImageView = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int homeLinearLayout = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int homeResultScreenButton = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int homeTextView = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int homeVLinearLayout = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int itemsLinearLayout = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int resultsLinearLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int resultsTextView = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Home = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Results = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
